### ISSUE TITLE
Configure double quotes or single quotes output

### ISSUE THREAD

**Issue by shawntabrizi** [LongTengDao/j-toml#18]
I am using this project to parse / lint TOML files generated by [Rust](https://www.rust-lang.org/).

Rust uses double quotes to surround all of their strings. For example, when doing `cargo init`:

```toml
[package]
name = "temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

However, when using `TOML.stringify`, the default character used is a single quote.

```javascript
let text = fs.readFileSync(file);
let toml = TOML.parse(text, { x: { comment: true } });
let new_text = TOML.stringify(toml, { newline: "\n", newlineAround: "section" });
fs.writeFileSync(file, new_text);
```

Output:

```toml

[package]
name = 'temp'
version = '0.1.0'
edition = '2021'

[dependencies]

```

Diff

```diff
diff --git a/Cargo.toml b/Cargo-new.toml
index 8dd49c0..dfc05d5 100644
--- a/Cargo.toml
+++ b/Cargo-new.toml
@@ -1,8 +1,7 @@
-[package]
-name = "temp"
-version = "0.1.0"
-edition = "2021"
 
-# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
+[package]
+name = 'temp'
+version = '0.1.0'
+edition = '2021'
 
 [dependencies]

```

It would be nice to be able to configure this to keep things more consistent in Rust projects.
