### ISSUE TITLE
Status of Single-line and Multiline Comments

### ISSUE THREAD

**Issue by shawntabrizi** [LongTengDao/j-toml#19]
I have read in the documentation that that parsing and handling comments is one of the "sore points".

Specifically, it seems your library only parses and allows for inline comments, whereas it is pretty regular to see TOML files with comments over the lines they are modifying, or even multiline comments which act as separators between sections of TOML configuration.

Examples of comments over the lines can be found in the TOML specification: https://toml.io/en/

```toml
# integers
int1 = +99
int2 = 42
int3 = 0
int4 = -17

# hexadecimal with prefix `0x`
hex1 = 0xDEADBEEF
hex2 = 0xdeadbeef
hex3 = 0xdead_beef

# octal with prefix `0o`
oct1 = 0o01234567
oct2 = 0o755
```

And a basic Rust toml file uses a multi-line "island" comment:

```toml
[package]
name = "temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

What are the current limitations around parsing and handling these TOML comments? Is this something that this library could support in the future?

If you have an idea how you would like it implemented, could you write some notes so maybe I (or others) could try a stab at it?

Thanks!

**Comment by LongTengDao** [comment]
Yes, of cause I also want to support over-line, "island" and multi-line comments.

The main difficulty I meet, is that there seems no good way to describe which does a comment belong to (while parsing or stringifying).

**Comment by shawntabrizi** [comment]
Yeah, totally understood. The island comments seem to be the hardest to handle here, but I think that you could create a few rules which would capture most situations.

For example, today you only capture inline comments, and drop the rest.

You could also enable a feature where single / multi-line comments are attached to the nearest TOML line below it, and the rest would be dropped just as before.

So using your example above, we would get:


```
stringify({
    a: {
        a: '1', [commentAbove('a')]: ' a \n a.a',
        b: {
            x: '1', [commentAbove('x')]: ' a.b',
            y: '1'
        }
    },
}
```

At least in this case, we capture what is arguably the most common kind of comment in the way that is most normally expected. Here we still drop the island comment, and the tricky comment at the end of the file, but this would be a large step forward from what is available today.

And, at the end, I believe more rules like this could be configurable as xOptions, allowing the user to play with the rules for their desired behavior.

**Comment by LongTengDao** [comment]
I think I need to confirm your final need about comment.

Firstly, `@ltd/j-toml` support any valid comment parsing; problem is how to remain it when stringify.

Here are two main cases to stringify a TOML document with comments: 1) a table parsed from existing file (which means you only want to change some value, and want to remain the comments without changes); 2) a brand new table with new structure, or change existing comments info.

If only 1st case is usually needed, then the mechanisms can be in black box; if both, then here muse be a good enough api, and I need to design it systematically.

**Comment by LongTengDao** [comment]
```toml
# overall

# a
# a.a
a.a = 1
# a.b
a.b.x = 1
a.b.y = 1
#a.b.z = 1
```

```
{
    [commentsInThis]: [ [' overall'], [' a',' a.a'], 'a', ['a.b.z = 1'] ],
    a: {
        [commentsInThis]: [ 'a', [' a.b'], 'b' ],
        a: 1,
        b: {
            x: 1,
            y: 1,
        },
    },
}
```

Does this look good enough? (Won't distinguish over-line comment and "island" comment, which can be designed, but I found it's easy to see mixing up in your samples.)
