### ISSUE TITLE
Maintain "style"

### ISSUE THREAD

**Issue by mustafa0x** [LongTengDao/j-toml#26]
Hi, thanks for the wonderful library.

```js
const doc = `title = "Development Page"
description = """
Multi
Line
Test
"""
`
const obj = toml.parse(doc, { joiner: "\n" });
obj.description = 'Multi\nLine\nTest\n1'
const out = toml.stringify(obj, { newline: "\n", T: " " });
```

Results in:

```toml
title = "Development Page"
description = "Multi\nLine\nTest\n1"
```

(description is no longer a multi-line string).

Similar applies to numbers (updating adds zeroes). Is there a way to maintain style even after editing? Even if it has to later be added in before converting back to toml.

Thanks!
